// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	ApiSecretScopes = "ApiSecret.Scopes"
)

// Asset defines model for Asset.
type Asset struct {
	// Amount OrderAmount converted to asset
	Amount *float32 `json:"Amount,omitempty"`

	// Blockchains the list of blockchains, on which this asset can be sent
	Blockchains *[]Blockchain `json:"Blockchains,omitempty"`

	// Code asset symbol, e.g. "USDC"
	Code *string `json:"Code,omitempty"`

	// DisplayDecimals how many decimal places to display in the UI
	DisplayDecimals *float32 `json:"DisplayDecimals,omitempty"`

	// IsStable whether or not this asset is a stablecoin
	IsStable *bool `json:"IsStable,omitempty"`

	// IsToken whether or not this asset is an ERC20 token
	IsToken *bool `json:"IsToken,omitempty"`

	// Name asset name, e.g. "USD Coin"
	Name *string `json:"Name,omitempty"`

	// Price the price of asset in orderCurrency
	Price *float32 `json:"Price,omitempty"`
}

// AssetListPostRequest defines model for AssetListPostRequest.
type AssetListPostRequest struct {
	MerchantId    string  `json:"MerchantId"`
	OrderAmount   float32 `json:"OrderAmount"`
	OrderCurrency *string `json:"OrderCurrency,omitempty"`
}

// Blockchain defines model for Blockchain.
type Blockchain struct {
	// ChainId EVM chain ID – only for EVM blockchains
	ChainId *float32 `json:"ChainId,omitempty"`

	// Code blockchain code, e.g. "ETH"
	Code *string `json:"Code,omitempty"`

	// ContractAddress contract address for payment settlement
	ContractAddress *string `json:"ContractAddress,omitempty"`

	// Decimals number of decimal places for the asset on this blockchain
	Decimals *float32 `json:"Decimals,omitempty"`

	// IsEvm whether or not this is an EVM-compatible blockchain
	IsEvm *bool `json:"IsEvm,omitempty"`

	// Name blockchain name, e.g. "Ethereum"
	Name *string `json:"Name,omitempty"`

	// TokenAddress smart contract address – only for ERC20 tokens
	TokenAddress *string `json:"TokenAddress,omitempty"`
}

// CancelPayoutPostRequest defines model for CancelPayoutPostRequest.
type CancelPayoutPostRequest struct {
	MerchantId *string `json:"MerchantId,omitempty"`
	PaymentId  *string `json:"PaymentId,omitempty"`
}

// CancelPostRequest defines model for CancelPostRequest.
type CancelPostRequest struct {
	MerchantId     *string `json:"MerchantId,omitempty"`
	OrderId        *string `json:"OrderId,omitempty"`
	SubscriptionId *string `json:"SubscriptionId,omitempty"`
}

// CreatePaymentPostRequest defines model for CreatePaymentPostRequest.
type CreatePaymentPostRequest struct {
	AssetCode      string  `json:"AssetCode"`
	BlockchainCode float32 `json:"BlockchainCode"`
	InvoiceId      string  `json:"InvoiceId"`
	IsEvm          string  `json:"IsEvm"`
	UserAddress    *string `json:"UserAddress,omitempty"`
}

// FindByHashPostRequest defines model for FindByHashPostRequest.
type FindByHashPostRequest struct {
	BlockchainHash *string `json:"BlockchainHash,omitempty"`
	MerchantId     string  `json:"MerchantId"`
}

// FindByHashPostResponseBody defines model for FindByHashPostResponseBody.
type FindByHashPostResponseBody struct {
	// IsFound whether or not this transaction hash exists
	IsFound *bool `json:"IsFound,omitempty"`

	// Transaction transaction information
	Transaction *struct {
		// Amount the amount of asset received
		Amount *float32 `json:"Amount,omitempty"`

		// AssetCode asset code
		AssetCode *string `json:"AssetCode,omitempty"`

		// BlockNumber blockchain block height
		BlockNumber *float32 `json:"BlockNumber,omitempty"`

		// BlockchainCode blockchain code
		BlockchainCode *string `json:"BlockchainCode,omitempty"`

		// BlockchainHash blockchain transaction hash (a.k.a. blockchain transaction ID)
		BlockchainHash *string `json:"BlockchainHash,omitempty"`

		// Fee the amount of the commission fee collected
		Fee *string `json:"Fee,omitempty"`

		// Id transaction ID (generated by ATLOS)
		Id *string `json:"Id,omitempty"`

		// MerchantId your merchant ID
		MerchantId *string `json:"MerchantId,omitempty"`

		// OrderId the order ID you passed to the widget or the API as orderId
		OrderId *string `json:"OrderId,omitempty"`

		// RecipientAddress the receiving wallet address
		RecipientAddress *string `json:"RecipientAddress,omitempty"`

		// SenderAddress for EVM blockchains, the sender's wallet address
		SenderAddress *string `json:"SenderAddress,omitempty"`

		// Status 100 (success)
		Status *float32 `json:"Status,omitempty"`

		// SubscriptionId subscription ID (generated by ATLOS)
		SubscriptionId *string `json:"SubscriptionId,omitempty"`

		// TimeSent time when the transaction was recorded in a block
		TimeSent *string `json:"TimeSent,omitempty"`
	} `json:"Transaction,omitempty"`
}

// InvoiceCancelPostRequest defines model for InvoiceCancelPostRequest.
type InvoiceCancelPostRequest struct {
	InvoiceId  *string `json:"InvoiceId,omitempty"`
	MerchantId *string `json:"MerchantId,omitempty"`
}

// InvoiceCreatePostRequest defines model for InvoiceCreatePostRequest.
type InvoiceCreatePostRequest struct {
	Memo              *string `json:"Memo,omitempty"`
	MerchantId        string  `json:"MerchantId"`
	OrderAmount       float32 `json:"OrderAmount"`
	OrderCurrency     *string `json:"OrderCurrency,omitempty"`
	OrderId           *string `json:"OrderId,omitempty"`
	PostbackUrl       *string `json:"PostbackUrl,omitempty"`
	ResetSubscription *bool   `json:"ResetSubscription,omitempty"`
	SendEmail         *bool   `json:"SendEmail,omitempty"`
	Subscription      *string `json:"Subscription,omitempty"`
	TimeExpire        *string `json:"TimeExpire,omitempty"`
	UserEmail         *string `json:"UserEmail,omitempty"`
	UserName          *string `json:"UserName,omitempty"`
}

// InvoiceResponse defines model for InvoiceResponse.
type InvoiceResponse struct {
	// Id invoice ID
	Id *string `json:"Id,omitempty"`

	// PaymentLink URL of the payment link
	PaymentLink *string `json:"PaymentLink,omitempty"`
}

// Payment defines model for Payment.
type Payment struct {
	// Amount how much asset to send in a string format without decimal point
	Amount *string `json:"Amount,omitempty"`

	// AssetCode asset symbol, e.g. "USDC"
	AssetCode *string `json:"AssetCode,omitempty"`

	// BlockchainCode blockchain code, e.g. "ETH"
	BlockchainCode *float32 `json:"BlockchainCode,omitempty"`

	// Fee how much commission fee will be taken for this payment
	Fee *string `json:"Fee,omitempty"`

	// Id payment ID
	Id *string `json:"Id,omitempty"`

	// RecipientAddress the wallet address where to send the asset
	RecipientAddress *string `json:"RecipientAddress,omitempty"`

	// Status payment status (always New here)
	Status *string `json:"Status,omitempty"`

	// Txid blockchain transaction hash – only if transaction is in the mempool or in a block
	Txid *string `json:"Txid,omitempty"`
}

// PaymentGetPostRequest defines model for PaymentGetPostRequest.
type PaymentGetPostRequest struct {
	PaymentId string `json:"PaymentId"`
}

// PaymentWebSocketPostRequest defines model for PaymentWebSocketPostRequest.
type PaymentWebSocketPostRequest struct {
	PaymentId string `json:"paymentId"`
}

// SendTokenPostRequest defines model for SendTokenPostRequest.
type SendTokenPostRequest struct {
	AssetCode        string   `json:"AssetCode"`
	BlockchainCode   string   `json:"BlockchainCode"`
	Memo             *string  `json:"Memo,omitempty"`
	MerchantId       string   `json:"MerchantId"`
	OrderAmount      *float32 `json:"OrderAmount,omitempty"`
	OrderCurrency    *string  `json:"OrderCurrency,omitempty"`
	OrderId          *string  `json:"OrderId,omitempty"`
	PostbackUrl      *string  `json:"PostbackUrl,omitempty"`
	RecipientAddress string   `json:"RecipientAddress"`
	SendEmail        *bool    `json:"SendEmail,omitempty"`
	TimeExpire       *string  `json:"TimeExpire,omitempty"`
	TokenAmount      *float32 `json:"TokenAmount,omitempty"`
	UserEmail        *string  `json:"UserEmail,omitempty"`
	UserName         *string  `json:"UserName,omitempty"`
}

// SendTokenPostResponseBody defines model for SendTokenPostResponseBody.
type SendTokenPostResponseBody struct {
	// AssetCode asset code
	AssetCode *string `json:"AssetCode,omitempty"`

	// BlockchainCode blockchain code
	BlockchainCode *string `json:"BlockchainCode,omitempty"`

	// Id invoice ID
	Id *string `json:"Id,omitempty"`

	// RecipientAddress recipient wallet address
	RecipientAddress *string `json:"RecipientAddress,omitempty"`

	// TokenAmount the amount of asset sent
	TokenAmount *string `json:"TokenAmount,omitempty"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount the amount of asset received
	Amount *float32 `json:"Amount,omitempty"`

	// AssetCode asset code
	AssetCode *string `json:"AssetCode,omitempty"`

	// BlockNumber blockchain block height
	BlockNumber *float32 `json:"BlockNumber,omitempty"`

	// BlockchainCode blockchain code
	BlockchainCode *string `json:"BlockchainCode,omitempty"`

	// BlockchainHash blockchain transaction hash (a.k.a. blockchain transaction ID)
	BlockchainHash *string `json:"BlockchainHash,omitempty"`

	// Fee the amount of the commission fee collected
	Fee *string `json:"Fee,omitempty"`

	// Id transaction ID (generated by ATLOS)
	Id *string `json:"Id,omitempty"`

	// MerchantId your merchant ID
	MerchantId *string `json:"MerchantId,omitempty"`

	// OrderId the order ID you passed to the widget or the API as orderId
	OrderId *string `json:"OrderId,omitempty"`

	// RecipientAddress the receiving wallet address
	RecipientAddress *string `json:"RecipientAddress,omitempty"`

	// SenderAddress for EVM blockchains, the sender's wallet address
	SenderAddress *string `json:"SenderAddress,omitempty"`

	// Status 100 (success)
	Status *float32 `json:"Status,omitempty"`

	// SubscriptionId subscription ID (generated by ATLOS)
	SubscriptionId *string `json:"SubscriptionId,omitempty"`

	// TimeSent time when the transaction was recorded in a block
	TimeSent *string `json:"TimeSent,omitempty"`
}

// TransactionListPostRequest defines model for TransactionListPostRequest.
type TransactionListPostRequest struct {
	MerchantId string   `json:"MerchantId"`
	Skip       *float32 `json:"Skip,omitempty"`
	Take       *float32 `json:"Take,omitempty"`
	TimeFinish *string  `json:"TimeFinish,omitempty"`
	TimeStart  *string  `json:"TimeStart,omitempty"`
}

// TransactionListPostResponseBody defines model for TransactionListPostResponseBody.
type TransactionListPostResponseBody struct {
	// TotalCount total number of transactions during the time period
	TotalCount *float32 `json:"TotalCount,omitempty"`

	// Transactions the list of transactions
	Transactions *[]Transaction `json:"Transactions,omitempty"`
}

// AssetListPostJSONRequestBody defines body for AssetListPost for application/json ContentType.
type AssetListPostJSONRequestBody = AssetListPostRequest

// InvoiceCancelPostJSONRequestBody defines body for InvoiceCancelPost for application/json ContentType.
type InvoiceCancelPostJSONRequestBody = InvoiceCancelPostRequest

// InvoiceCreatePostJSONRequestBody defines body for InvoiceCreatePost for application/json ContentType.
type InvoiceCreatePostJSONRequestBody = InvoiceCreatePostRequest

// CreatePaymentPostJSONRequestBody defines body for CreatePaymentPost for application/json ContentType.
type CreatePaymentPostJSONRequestBody = CreatePaymentPostRequest

// PaymentGetPostJSONRequestBody defines body for PaymentGetPost for application/json ContentType.
type PaymentGetPostJSONRequestBody = PaymentGetPostRequest

// PaymentWebSocketPostJSONRequestBody defines body for PaymentWebSocketPost for application/json ContentType.
type PaymentWebSocketPostJSONRequestBody = PaymentWebSocketPostRequest

// CancelPostJSONRequestBody defines body for CancelPost for application/json ContentType.
type CancelPostJSONRequestBody = CancelPostRequest

// FindByHashPostJSONRequestBody defines body for FindByHashPost for application/json ContentType.
type FindByHashPostJSONRequestBody = FindByHashPostRequest

// TransactionListPostJSONRequestBody defines body for TransactionListPost for application/json ContentType.
type TransactionListPostJSONRequestBody = TransactionListPostRequest

// CancelPayoutPostJSONRequestBody defines body for CancelPayoutPost for application/json ContentType.
type CancelPayoutPostJSONRequestBody = CancelPayoutPostRequest

// SendTokenPostJSONRequestBody defines body for SendTokenPost for application/json ContentType.
type SendTokenPostJSONRequestBody = SendTokenPostRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AssetListPostWithBody request with any body
	AssetListPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AssetListPost(ctx context.Context, body AssetListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InvoiceCancelPostWithBody request with any body
	InvoiceCancelPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InvoiceCancelPost(ctx context.Context, body InvoiceCancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InvoiceCreatePostWithBody request with any body
	InvoiceCreatePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InvoiceCreatePost(ctx context.Context, body InvoiceCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePaymentPostWithBody request with any body
	CreatePaymentPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePaymentPost(ctx context.Context, body CreatePaymentPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PaymentGetPostWithBody request with any body
	PaymentGetPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PaymentGetPost(ctx context.Context, body PaymentGetPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PaymentWebSocketPostWithBody request with any body
	PaymentWebSocketPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PaymentWebSocketPost(ctx context.Context, body PaymentWebSocketPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelPostWithBody request with any body
	CancelPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CancelPost(ctx context.Context, body CancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindByHashPostWithBody request with any body
	FindByHashPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FindByHashPost(ctx context.Context, body FindByHashPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TransactionListPostWithBody request with any body
	TransactionListPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TransactionListPost(ctx context.Context, body TransactionListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelPayoutPostWithBody request with any body
	CancelPayoutPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CancelPayoutPost(ctx context.Context, body CancelPayoutPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendTokenPostWithBody request with any body
	SendTokenPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendTokenPost(ctx context.Context, body SendTokenPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AssetListPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssetListPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AssetListPost(ctx context.Context, body AssetListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssetListPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InvoiceCancelPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInvoiceCancelPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InvoiceCancelPost(ctx context.Context, body InvoiceCancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInvoiceCancelPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InvoiceCreatePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInvoiceCreatePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InvoiceCreatePost(ctx context.Context, body InvoiceCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInvoiceCreatePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePaymentPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePaymentPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePaymentPost(ctx context.Context, body CreatePaymentPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePaymentPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PaymentGetPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentGetPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PaymentGetPost(ctx context.Context, body PaymentGetPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentGetPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PaymentWebSocketPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentWebSocketPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PaymentWebSocketPost(ctx context.Context, body PaymentWebSocketPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentWebSocketPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelPost(ctx context.Context, body CancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindByHashPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindByHashPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindByHashPost(ctx context.Context, body FindByHashPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindByHashPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransactionListPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransactionListPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransactionListPost(ctx context.Context, body TransactionListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransactionListPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelPayoutPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelPayoutPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelPayoutPost(ctx context.Context, body CancelPayoutPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelPayoutPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendTokenPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendTokenPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendTokenPost(ctx context.Context, body SendTokenPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendTokenPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAssetListPostRequest calls the generic AssetListPost builder with application/json body
func NewAssetListPostRequest(server string, body AssetListPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAssetListPostRequestWithBody(server, "application/json", bodyReader)
}

// NewAssetListPostRequestWithBody generates requests for AssetListPost with any type of body
func NewAssetListPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Asset/List")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInvoiceCancelPostRequest calls the generic InvoiceCancelPost builder with application/json body
func NewInvoiceCancelPostRequest(server string, body InvoiceCancelPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInvoiceCancelPostRequestWithBody(server, "application/json", bodyReader)
}

// NewInvoiceCancelPostRequestWithBody generates requests for InvoiceCancelPost with any type of body
func NewInvoiceCancelPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Invoice/Cancel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInvoiceCreatePostRequest calls the generic InvoiceCreatePost builder with application/json body
func NewInvoiceCreatePostRequest(server string, body InvoiceCreatePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInvoiceCreatePostRequestWithBody(server, "application/json", bodyReader)
}

// NewInvoiceCreatePostRequestWithBody generates requests for InvoiceCreatePost with any type of body
func NewInvoiceCreatePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Invoice/Create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreatePaymentPostRequest calls the generic CreatePaymentPost builder with application/json body
func NewCreatePaymentPostRequest(server string, body CreatePaymentPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePaymentPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePaymentPostRequestWithBody generates requests for CreatePaymentPost with any type of body
func NewCreatePaymentPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Payment/Create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPaymentGetPostRequest calls the generic PaymentGetPost builder with application/json body
func NewPaymentGetPostRequest(server string, body PaymentGetPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPaymentGetPostRequestWithBody(server, "application/json", bodyReader)
}

// NewPaymentGetPostRequestWithBody generates requests for PaymentGetPost with any type of body
func NewPaymentGetPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Payment/Get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPaymentWebSocketPostRequest calls the generic PaymentWebSocketPost builder with application/json body
func NewPaymentWebSocketPostRequest(server string, body PaymentWebSocketPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPaymentWebSocketPostRequestWithBody(server, "application/json", bodyReader)
}

// NewPaymentWebSocketPostRequestWithBody generates requests for PaymentWebSocketPost with any type of body
func NewPaymentWebSocketPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Payment/WebSocket")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelPostRequest calls the generic CancelPost builder with application/json body
func NewCancelPostRequest(server string, body CancelPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCancelPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCancelPostRequestWithBody generates requests for CancelPost with any type of body
func NewCancelPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Subscription/Cancel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFindByHashPostRequest calls the generic FindByHashPost builder with application/json body
func NewFindByHashPostRequest(server string, body FindByHashPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindByHashPostRequestWithBody(server, "application/json", bodyReader)
}

// NewFindByHashPostRequestWithBody generates requests for FindByHashPost with any type of body
func NewFindByHashPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Transaction/FindByHash")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTransactionListPostRequest calls the generic TransactionListPost builder with application/json body
func NewTransactionListPostRequest(server string, body TransactionListPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTransactionListPostRequestWithBody(server, "application/json", bodyReader)
}

// NewTransactionListPostRequestWithBody generates requests for TransactionListPost with any type of body
func NewTransactionListPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Transaction/List")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelPayoutPostRequest calls the generic CancelPayoutPost builder with application/json body
func NewCancelPayoutPostRequest(server string, body CancelPayoutPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCancelPayoutPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCancelPayoutPostRequestWithBody generates requests for CancelPayoutPost with any type of body
func NewCancelPayoutPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Wallet/CancelPayout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSendTokenPostRequest calls the generic SendTokenPost builder with application/json body
func NewSendTokenPostRequest(server string, body SendTokenPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendTokenPostRequestWithBody(server, "application/json", bodyReader)
}

// NewSendTokenPostRequestWithBody generates requests for SendTokenPost with any type of body
func NewSendTokenPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Wallet/SendToken")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AssetListPostWithBodyWithResponse request with any body
	AssetListPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssetListPostResponse, error)

	AssetListPostWithResponse(ctx context.Context, body AssetListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*AssetListPostResponse, error)

	// InvoiceCancelPostWithBodyWithResponse request with any body
	InvoiceCancelPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InvoiceCancelPostResponse, error)

	InvoiceCancelPostWithResponse(ctx context.Context, body InvoiceCancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*InvoiceCancelPostResponse, error)

	// InvoiceCreatePostWithBodyWithResponse request with any body
	InvoiceCreatePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InvoiceCreatePostResponse, error)

	InvoiceCreatePostWithResponse(ctx context.Context, body InvoiceCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*InvoiceCreatePostResponse, error)

	// CreatePaymentPostWithBodyWithResponse request with any body
	CreatePaymentPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePaymentPostResponse, error)

	CreatePaymentPostWithResponse(ctx context.Context, body CreatePaymentPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePaymentPostResponse, error)

	// PaymentGetPostWithBodyWithResponse request with any body
	PaymentGetPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PaymentGetPostResponse, error)

	PaymentGetPostWithResponse(ctx context.Context, body PaymentGetPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PaymentGetPostResponse, error)

	// PaymentWebSocketPostWithBodyWithResponse request with any body
	PaymentWebSocketPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PaymentWebSocketPostResponse, error)

	PaymentWebSocketPostWithResponse(ctx context.Context, body PaymentWebSocketPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PaymentWebSocketPostResponse, error)

	// CancelPostWithBodyWithResponse request with any body
	CancelPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelPostResponse, error)

	CancelPostWithResponse(ctx context.Context, body CancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelPostResponse, error)

	// FindByHashPostWithBodyWithResponse request with any body
	FindByHashPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindByHashPostResponse, error)

	FindByHashPostWithResponse(ctx context.Context, body FindByHashPostJSONRequestBody, reqEditors ...RequestEditorFn) (*FindByHashPostResponse, error)

	// TransactionListPostWithBodyWithResponse request with any body
	TransactionListPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransactionListPostResponse, error)

	TransactionListPostWithResponse(ctx context.Context, body TransactionListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*TransactionListPostResponse, error)

	// CancelPayoutPostWithBodyWithResponse request with any body
	CancelPayoutPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelPayoutPostResponse, error)

	CancelPayoutPostWithResponse(ctx context.Context, body CancelPayoutPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelPayoutPostResponse, error)

	// SendTokenPostWithBodyWithResponse request with any body
	SendTokenPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendTokenPostResponse, error)

	SendTokenPostWithResponse(ctx context.Context, body SendTokenPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SendTokenPostResponse, error)
}

type AssetListPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Asset
}

// Status returns HTTPResponse.Status
func (r AssetListPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AssetListPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InvoiceCancelPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InvoiceCancelPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InvoiceCancelPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InvoiceCreatePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InvoiceResponse
}

// Status returns HTTPResponse.Status
func (r InvoiceCreatePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InvoiceCreatePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePaymentPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Payment
}

// Status returns HTTPResponse.Status
func (r CreatePaymentPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePaymentPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PaymentGetPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Payment
}

// Status returns HTTPResponse.Status
func (r PaymentGetPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PaymentGetPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PaymentWebSocketPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PaymentWebSocketPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PaymentWebSocketPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CancelPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindByHashPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FindByHashPostResponseBody
}

// Status returns HTTPResponse.Status
func (r FindByHashPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindByHashPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TransactionListPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionListPostResponseBody
}

// Status returns HTTPResponse.Status
func (r TransactionListPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TransactionListPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelPayoutPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CancelPayoutPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelPayoutPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendTokenPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SendTokenPostResponseBody
}

// Status returns HTTPResponse.Status
func (r SendTokenPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendTokenPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AssetListPostWithBodyWithResponse request with arbitrary body returning *AssetListPostResponse
func (c *ClientWithResponses) AssetListPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssetListPostResponse, error) {
	rsp, err := c.AssetListPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssetListPostResponse(rsp)
}

func (c *ClientWithResponses) AssetListPostWithResponse(ctx context.Context, body AssetListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*AssetListPostResponse, error) {
	rsp, err := c.AssetListPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssetListPostResponse(rsp)
}

// InvoiceCancelPostWithBodyWithResponse request with arbitrary body returning *InvoiceCancelPostResponse
func (c *ClientWithResponses) InvoiceCancelPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InvoiceCancelPostResponse, error) {
	rsp, err := c.InvoiceCancelPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInvoiceCancelPostResponse(rsp)
}

func (c *ClientWithResponses) InvoiceCancelPostWithResponse(ctx context.Context, body InvoiceCancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*InvoiceCancelPostResponse, error) {
	rsp, err := c.InvoiceCancelPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInvoiceCancelPostResponse(rsp)
}

// InvoiceCreatePostWithBodyWithResponse request with arbitrary body returning *InvoiceCreatePostResponse
func (c *ClientWithResponses) InvoiceCreatePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InvoiceCreatePostResponse, error) {
	rsp, err := c.InvoiceCreatePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInvoiceCreatePostResponse(rsp)
}

func (c *ClientWithResponses) InvoiceCreatePostWithResponse(ctx context.Context, body InvoiceCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*InvoiceCreatePostResponse, error) {
	rsp, err := c.InvoiceCreatePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInvoiceCreatePostResponse(rsp)
}

// CreatePaymentPostWithBodyWithResponse request with arbitrary body returning *CreatePaymentPostResponse
func (c *ClientWithResponses) CreatePaymentPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePaymentPostResponse, error) {
	rsp, err := c.CreatePaymentPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePaymentPostResponse(rsp)
}

func (c *ClientWithResponses) CreatePaymentPostWithResponse(ctx context.Context, body CreatePaymentPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePaymentPostResponse, error) {
	rsp, err := c.CreatePaymentPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePaymentPostResponse(rsp)
}

// PaymentGetPostWithBodyWithResponse request with arbitrary body returning *PaymentGetPostResponse
func (c *ClientWithResponses) PaymentGetPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PaymentGetPostResponse, error) {
	rsp, err := c.PaymentGetPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentGetPostResponse(rsp)
}

func (c *ClientWithResponses) PaymentGetPostWithResponse(ctx context.Context, body PaymentGetPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PaymentGetPostResponse, error) {
	rsp, err := c.PaymentGetPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentGetPostResponse(rsp)
}

// PaymentWebSocketPostWithBodyWithResponse request with arbitrary body returning *PaymentWebSocketPostResponse
func (c *ClientWithResponses) PaymentWebSocketPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PaymentWebSocketPostResponse, error) {
	rsp, err := c.PaymentWebSocketPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentWebSocketPostResponse(rsp)
}

func (c *ClientWithResponses) PaymentWebSocketPostWithResponse(ctx context.Context, body PaymentWebSocketPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PaymentWebSocketPostResponse, error) {
	rsp, err := c.PaymentWebSocketPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentWebSocketPostResponse(rsp)
}

// CancelPostWithBodyWithResponse request with arbitrary body returning *CancelPostResponse
func (c *ClientWithResponses) CancelPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelPostResponse, error) {
	rsp, err := c.CancelPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelPostResponse(rsp)
}

func (c *ClientWithResponses) CancelPostWithResponse(ctx context.Context, body CancelPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelPostResponse, error) {
	rsp, err := c.CancelPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelPostResponse(rsp)
}

// FindByHashPostWithBodyWithResponse request with arbitrary body returning *FindByHashPostResponse
func (c *ClientWithResponses) FindByHashPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindByHashPostResponse, error) {
	rsp, err := c.FindByHashPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindByHashPostResponse(rsp)
}

func (c *ClientWithResponses) FindByHashPostWithResponse(ctx context.Context, body FindByHashPostJSONRequestBody, reqEditors ...RequestEditorFn) (*FindByHashPostResponse, error) {
	rsp, err := c.FindByHashPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindByHashPostResponse(rsp)
}

// TransactionListPostWithBodyWithResponse request with arbitrary body returning *TransactionListPostResponse
func (c *ClientWithResponses) TransactionListPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransactionListPostResponse, error) {
	rsp, err := c.TransactionListPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransactionListPostResponse(rsp)
}

func (c *ClientWithResponses) TransactionListPostWithResponse(ctx context.Context, body TransactionListPostJSONRequestBody, reqEditors ...RequestEditorFn) (*TransactionListPostResponse, error) {
	rsp, err := c.TransactionListPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransactionListPostResponse(rsp)
}

// CancelPayoutPostWithBodyWithResponse request with arbitrary body returning *CancelPayoutPostResponse
func (c *ClientWithResponses) CancelPayoutPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelPayoutPostResponse, error) {
	rsp, err := c.CancelPayoutPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelPayoutPostResponse(rsp)
}

func (c *ClientWithResponses) CancelPayoutPostWithResponse(ctx context.Context, body CancelPayoutPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelPayoutPostResponse, error) {
	rsp, err := c.CancelPayoutPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelPayoutPostResponse(rsp)
}

// SendTokenPostWithBodyWithResponse request with arbitrary body returning *SendTokenPostResponse
func (c *ClientWithResponses) SendTokenPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendTokenPostResponse, error) {
	rsp, err := c.SendTokenPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendTokenPostResponse(rsp)
}

func (c *ClientWithResponses) SendTokenPostWithResponse(ctx context.Context, body SendTokenPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SendTokenPostResponse, error) {
	rsp, err := c.SendTokenPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendTokenPostResponse(rsp)
}

// ParseAssetListPostResponse parses an HTTP response from a AssetListPostWithResponse call
func ParseAssetListPostResponse(rsp *http.Response) (*AssetListPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AssetListPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Asset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInvoiceCancelPostResponse parses an HTTP response from a InvoiceCancelPostWithResponse call
func ParseInvoiceCancelPostResponse(rsp *http.Response) (*InvoiceCancelPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InvoiceCancelPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseInvoiceCreatePostResponse parses an HTTP response from a InvoiceCreatePostWithResponse call
func ParseInvoiceCreatePostResponse(rsp *http.Response) (*InvoiceCreatePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InvoiceCreatePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreatePaymentPostResponse parses an HTTP response from a CreatePaymentPostWithResponse call
func ParseCreatePaymentPostResponse(rsp *http.Response) (*CreatePaymentPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePaymentPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Payment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePaymentGetPostResponse parses an HTTP response from a PaymentGetPostWithResponse call
func ParsePaymentGetPostResponse(rsp *http.Response) (*PaymentGetPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PaymentGetPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Payment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePaymentWebSocketPostResponse parses an HTTP response from a PaymentWebSocketPostWithResponse call
func ParsePaymentWebSocketPostResponse(rsp *http.Response) (*PaymentWebSocketPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PaymentWebSocketPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCancelPostResponse parses an HTTP response from a CancelPostWithResponse call
func ParseCancelPostResponse(rsp *http.Response) (*CancelPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindByHashPostResponse parses an HTTP response from a FindByHashPostWithResponse call
func ParseFindByHashPostResponse(rsp *http.Response) (*FindByHashPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindByHashPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FindByHashPostResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTransactionListPostResponse parses an HTTP response from a TransactionListPostWithResponse call
func ParseTransactionListPostResponse(rsp *http.Response) (*TransactionListPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TransactionListPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionListPostResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCancelPayoutPostResponse parses an HTTP response from a CancelPayoutPostWithResponse call
func ParseCancelPayoutPostResponse(rsp *http.Response) (*CancelPayoutPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelPayoutPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSendTokenPostResponse parses an HTTP response from a SendTokenPostWithResponse call
func ParseSendTokenPostResponse(rsp *http.Response) (*SendTokenPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendTokenPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SendTokenPostResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
