package main

import (
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"os"
	"text/template"

	internalclient "go.lumeweb.com/atlos-sdk/internal/client"
)

var goTemplate = `// Code generated by scripts/fetch-assets.go
// DO NOT EDIT

package atlos

import (
	internalclient "go.lumeweb.com/atlos-sdk/internal/client"
)

// AssetListResponse represents the response structure for asset list API
type AssetListResponse struct {
	Assets []internalclient.Asset
}

// AssetsFromAtlas contains the asset list fetched from Atlas API
var AssetsFromAtlas = []internalclient.Asset{
{{- range $i, $asset := .Assets }}
	{
		{{- if $asset.Amount }}
		Amount: new(float32({{$asset.Amount}})),
		{{- end}}
		{{if $asset.Blockchains -}}
		Blockchains: &[]internalclient.Blockchain{
			{{- range $j, $chain := $asset.Blockchains }}
			{
				{{- if $chain.Code }}
				Code: new("{{$chain.Code}}"),
				{{- end}}
				{{- if $chain.Name }}
				Name: new("{{$chain.Name}}"),
				{{- end}}
				{{- if $chain.Decimals }}
				Decimals: new(float32({{$chain.Decimals}})),
				{{- end}}
				{{- if $chain.IsEvm }}
				IsEvm: new(bool({{$chain.IsEvm}})),
				{{- end}}
				{{- if $chain.ChainId }}
				ChainId: new(float32({{$chain.ChainId}})),
				{{- end}}
				{{- if $chain.TokenAddress }}
				TokenAddress: new("{{$chain.TokenAddress}}"),
				{{- end}}
				{{- if $chain.ContractAddress }}
				ContractAddress: new("{{$chain.ContractAddress}}"),
				{{- end}}
			},
			{{- end}}
		},
		{{- end}}
		{{- if $asset.Code }}
		Code: new("{{$asset.Code}}"),
		{{- end}}
		{{- if $asset.DisplayDecimals }}
		DisplayDecimals: new(float32({{$asset.DisplayDecimals}})),
		{{- end}}
		{{- if $asset.IsStable }}
		IsStable: new(bool({{$asset.IsStable}})),
		{{- end }}
		{{- if $asset.IsToken }}
		IsToken: new(bool({{$asset.IsToken}})),
		{{- end }}
		{{- if $asset.Name }}
		Name: new("{{$asset.Name}}"),
		{{- end }}
		{{- if $asset.Price }}
		Price: new(float32({{$asset.Price}})),
		{{- end }}
	},
{{- end }}
}
`

func main() {
	apiSecret := os.Getenv("ATLOS_API_SECRET")
	if apiSecret == "" {
		log.Fatalf("ATLOS_API_SECRET environment variable is required")
	}

	merchantId := os.Getenv("ATLOS_MERCHANT_ID")
	if merchantId == "" {
		log.Fatalf("ATLOS_MERCHANT_ID environment variable is required")
	}

	reqBody := internalclient.AssetListPostRequest{
		MerchantId:  merchantId,
		OrderAmount: 100.0,
	}

	bodyJSON, err := json.Marshal(reqBody)
	if err != nil {
		log.Fatalf("Failed to marshal request body: %v", err)
	}

	req, err := http.NewRequest("POST", "https://api.atlos.io/gateway/rest/Asset/List", bytes.NewReader(bodyJSON))
	if err != nil {
		log.Fatalf("Failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("ApiSecret", apiSecret)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Fatalf("Failed to make request: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		log.Fatalf("API returned status %d: %s", resp.StatusCode, string(body))
	}

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("Failed to read response body: %v", err)
	}

	var assets []internalclient.Asset
	if err := json.Unmarshal(respBody, &assets); err != nil {
		log.Fatalf("Failed to unmarshal response: %v", err)
	}

	response := struct {
		Assets []internalclient.Asset
	}{
		Assets: assets,
	}

	tmpl, err := template.New("assets").Parse(goTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	if err := tmpl.Execute(os.Stdout, response); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}
}
